/** Daftar isi buku siswa Kurikulum Merdeka (Pusat Perbukuan, edisi terbaru yang terverifikasi). */

const PAI = "Pendidikan Agama Islam dan Budi Pekerti";
const PJOK = "Pendidikan Jasmani, Olahraga, dan Kesehatan";
const IPAS = "Ilmu Pengetahuan Alam dan Sosial (IPAS)";

export const BAB_BUKU_SISWA: Record<string, Record<string, string[]>> = {
  "1 SD": {
    [PAI]: [
      "Bab 1: Aku Cinta Al-Qur’an",
      "Bab 2: Mengenal Rukun Iman",
      "Bab 3: Aku Suka Membaca Basmalah dan Hamdalah",
      "Bab 4: Mengenal Rukun Islam",
      "Bab 5: Nabi dan Rasul Panutanku",
      "Bab 6: Al-Qur’an Pedoman Hidupku",
      "Bab 7: Kasih Sayang terhadap Sesama",
      "Bab 8: Aku Suka Berterima Kasih dan Disiplin",
      "Bab 9: Membiasakan Hidup Bersih",
      "Bab 10: Nabi Adam a.s. Manusia Pertama",
    ],
    "Pendidikan Pancasila": [
      "Bab 1: Aku dan Teman-Temanku",
      "Bab 2: Aku Patuh Pada Aturan",
      "Bab 3: Aku Mengenal Indonesia",
      "Bab 4: Aku dan Lingkunganku",
    ],
    "Bahasa Indonesia": [
      "Bab 1: Bunyi Apa?",
      "Bab 2: Ayo Bermain!",
      "Bab 3: Awas Kuman!",
      "Bab 4: Aku Bisa!",
      "Bab 5: Teman Baru",
      "Bab 6: Temanku Berbeda",
      "Bab 7: Aku Ingin",
      "Bab 8: Di Sekitar Rumah",
    ],
    Matematika: [
      "Bab 1: Ayo Membilang sampai dengan 10",
      "Bab 2: Penjumlahan sampai dengan 10",
      "Bab 3: Pengurangan sampai dengan 10",
      "Bab 4: Mengenal Bentuk",
      "Bab 5: Ayo Membilang sampai dengan 20",
      "Bab 6: Penjumlahan dan Pengurangan sampai dengan 20",
      "Bab 7: Mengukur Panjang Benda",
      "Bab 8: Mengenal Diagram",
    ],
    [PJOK]: [
      "Unit 1: Aktivitas Pola Gerak Dasar Lokomotor",
      "Unit 2: Aktivitas Pola Gerak Dasar Nonlokomotor",
      "Unit 3: Aktivitas Pola Gerak Dasar Manipulatif",
      "Unit 4: Aktivitas Senam",
      "Unit 5: Aktivitas Gerak Berirama",
      "Unit 6: Aktivitas Pengenalan Air",
      "Unit 7: Aktivitas Kebugaran Jasmani yang Berkaitan dengan Kesehatan",
      "Unit 8: Mengenal Bagian-Bagian Tubuh",
    ],
    "Bahasa Inggris": [
      "Unit 1: How are you?",
      "Unit 2: Hi, I am KIMI. Meow.",
      "Unit 3: My name is Joshua",
      "Unit 4: My number is ten",
      "Unit 5: I have four books",
      "Unit 6: My garden is colorful",
      "Unit 7: It is a big circle",
      "Unit 8: I have pencils",
      "Unit 9: At Cici’s farm",
      "Unit 10: She is Cici and he is Made",
      "Unit 11: Aisyah’s family",
      "Unit 12: She has some fruits",
      "Unit 13: I like fruits",
    ],
    "Seni dan Budaya": [
      "Bab 1: Menggambar dan Mewarnai",
      "Bab 2: Menyanyi Lagu Anak",
      "Bab 3: Gerak dan Tari",
      "Bab 4: Kerajinan dari Bahan Alam",
    ],
    Prakarya: [
      "Bab 1: Kerajinan Bahan Alam",
      "Bab 2: Kerajinan Bahan Buatan",
      "Bab 3: Rekayasa Sederhana",
      "Bab 4: Pengolahan Makanan",
    ],
    "Seni Rupa": [
      "Bab 1: Menggambar Imajinatif",
      "Bab 2: Mencetak Sederhana",
      "Bab 3: Kolase",
      "Bab 4: Membentuk dari Tanah Liat",
    ],
    "Seni Musik": [
      "Bab 1: Bernyanyi Lagu Anak",
      "Bab 2: Irama dan Birama",
      "Bab 3: Permainan Alat Musik Sederhana",
      "Bab 4: Ansambel Kelas",
    ],
    "Seni Tari": [
      "Bab 1: Gerak Dasar Tari",
      "Bab 2: Menirukan Gerak Alam",
      "Bab 3: Tari Kreasi Anak",
      "Bab 4: Pentas Mini",
    ],
    "Seni Teater": [
      "Bab 1: Bermain Peran",
      "Bab 2: Dongeng",
      "Bab 3: Suara dan Ekspresi",
      "Bab 4: Pementasan Kelas",
    ],
  },
  "2 SD": {
    [PAI]: [
      "Bab 1: Ayo Belajar Al-Qur’an",
      "Bab 2: Mari Mengenal Allah Swt.",
      "Bab 3: Ayo Berperilaku Terpuji",
      "Bab 4: Alhamdulillah, Aku Bisa Salat",
      "Bab 5: Asyiknya Belajar Kisah Nabi Nuh a.s.",
      "Bab 6: Senang Bisa Membaca Al-Qur’an",
      "Bab 7: Mari Mengenal Malaikat-Malaikat Allah",
      "Bab 8: Aku Senang Bisa Berakhlak Terpuji",
      "Bab 9: Ayo Zikir dan Doa Setelah Salat",
      "Bab 10: Asyiknya Belajar Kisah Ayah Para Nabi",
    ],
    "Pendidikan Pancasila": [
      "Bab 1: Aku Patuh Aturan",
      "Bab 2: Aku Berperilaku Pancasila",
      "Bab 3: Aku dan Teman-Temanku",
      "Bab 4: Aku Peduli Lingkungan",
    ],
    "Bahasa Indonesia": [
      "Bab 1: Mengenal Perasaan",
      "Bab 2: Menjaga Kesehatan",
      "Bab 3: Berhati-hati di Mana Saja",
      "Bab 4: Keluargaku Unik",
      "Bab 5: Berteman dalam Keragaman",
      "Bab 6: Bijak Memakai Uang",
      "Bab 7: Sayang Lingkungan",
      "Bab 8: Hobi yang Jadi Prestasi",
    ],
    Matematika: [
      "Bab 1: Bilangan 1 Sampai dengan 1.000",
      "Bab 2: Cara Berhitung",
      "Bab 3: Waktu dan Durasi",
      "Bab 4: Penjumlahan Bersusun",
      "Bab 5: Pengurangan Bersusun",
      "Bab 6: Panjang",
      "Bab 7: Tabel dan Grafik",
      "Bab 8: Banyaknya Air",
      "Bab 9: Penjumlahan dan Pengurangan",
      "Bab 10: Perkalian",
      "Bab 11: Segitiga dan Segiempat",
      "Bab 12: Bilangan sampai dengan 10.000",
      "Bab 13: Pecahan",
      "Bab 14: Bentuk-bentuk Kotak",
    ],
    [PJOK]: [
      "Bab 1: Aktivitas Pola Gerak Dasar Lokomotor",
      "Bab 2: Aktivitas Pola Gerak Dasar Non-Lokomotor",
      "Bab 3: Aktivitas Pola Gerak Dasar Manipulatif",
      "Bab 4: Aktivitas Gerak Dominan Senam",
      "Bab 5: Aktivitas Gerak Berirama",
      "Bab 6: Aktivitas Pengenalan Air",
      "Bab 7: Aktivitas Kebugaran Jasmani untuk Kesehatan",
      "Bab 8: Cara Menjaga Kebersihan Lingkungan",
    ],
    "Bahasa Inggris": [
      "Unit 1: Good morning, everyone",
      "Unit 2: This is my classroom",
      "Unit 3: I have a red bag",
      "Unit 4: It is a cat",
      "Unit 5: I like milk",
      "Unit 6: I can jump",
      "Unit 7: Where is my book?",
      "Unit 8: My house",
    ],
  },
  "3 SD": {
    [PAI]: [
      "Bab 1: Asyiknya Belajar Surah Al-‘Alaq",
      "Bab 2: Ayo Mengenal Tuhan Kita",
      "Bab 3: Perilaku Terpuji Adalah Kepribadianku",
      "Bab 4: Aku Bangga Mampu Berpuasa",
      "Bab 5: Aku Suka Belajar Sejarah Islam",
      "Bab 6: Senangnya Belajar Hadis",
      "Bab 7: Ayo Beriman Kepada Kitab-Kitab Allah Swt.",
      "Bab 8: Aku Senang Berkalimah Ṭayyibah",
      "Bab 9: Senangnya Salat Rawātib",
      "Bab 10: Nabi Muhammad saw. Rasulku",
    ],
    "Pendidikan Pancasila": [
      "Bab 1: Aku Anak Indonesia",
      "Bab 2: Aku Patuh Aturan",
      "Bab 3: Berbeda Itu Indah",
      "Bab 4: Ayo Mengenal Pancasila",
    ],
    "Bahasa Indonesia": [
      "Bab 1: Ayo, Main!",
      "Bab 2: Kawan Seiring",
      "Bab 3: Pengobar Semangat",
      "Bab 4: Senyum di Sekitarku",
      "Bab 5: Bola-Bola Cokelat",
      "Bab 6: Tersesat",
      "Bab 7: Aku dan si Merah",
      "Bab 8: Sahabat dari Seberang",
    ],
    Matematika: [
      "Bab 1: Bilangan Cacah sampai 1.000",
      "Bab 2: Kalimat Matematika",
      "Bab 3: Pengukuran Panjang dan Berat",
      "Bab 4: Unsur-Unsur Bangun Datar",
      "Bab 5: Penyajian Data dalam Tabel",
    ],
    [IPAS]: [
      "Bab 1: Mari Kenali Hewan di Sekitar Kita",
      "Bab 2: Ayo, Mengenal Siklus pada Makhluk Hidup",
      "Bab 3: Hidup Bersama Alam",
      "Bab 4: Berkenalan dengan Energi",
      "Bab 5: Aku dan Lingkungan Sekitarku",
      "Bab 6: Aku Bagian dari Masyarakat",
      "Bab 7: Cerita dari Kampung Halaman",
      "Bab 8: Bentang Alam Indonesia",
    ],
    "Bahasa Inggris": [
      "Unit 1: I like Mi Aceh",
      "Unit 2: I don’t like rice",
      "Unit 3: I have fried chicken for breakfast",
      "Unit 4: Do you like swimming",
      "Unit 5: I like riding a bike on Sunday",
      "Unit 6: Is it canteen",
    ],
    [PJOK]: [
      "Bab 1: Aktivitas Pola Gerak Dasar Lokomotor",
      "Bab 2: Aktivitas Pola Gerak Dasar Nonlokomotor",
      "Bab 3: Aktivitas Pola Gerak Dasar Manipulatif",
      "Bab 4: Aktivitas Senam",
      "Bab 5: Aktivitas Gerak Berirama",
      "Bab 6: Aktivitas Permainan di Air",
      "Bab 7: Aktivitas Kebugaran Jasmani",
      "Bab 8: Menjaga Kebersihan Diri",
    ],
  },
  "4 SD": {
    [PAI]: [
      "Bab 1: Mari Kita Mengaji dan Mengkaji Q.S. Al-Ḥujurat 49:13 dan Hadis tentang Keragaman",
      "Bab 2: Teladan Mulia Asmaulhusna",
      "Bab 3: Indahnya Saling Menghargai dalam Keragaman",
      "Bab 4: Menyambut Usia Baligh",
      "Bab 5: Kisah Hijrah Nabi Muhammad saw. ke Madinah",
      "Bab 6: Mari Mengaji dan Mengkaji Q.S. At-Tin dan Hadis tentang Silaturahmi",
      "Bab 7: Beriman Kepada Rasul-Rasul Allah",
      "Bab 8: Aku Anak Saleh",
      "Bab 9: Mengenal Salat Jumat, Duha dan Tahajud",
      "Bab 10: Kisah Nabi Muhammad saw. Membangun Kota Madinah",
    ],
    "Pendidikan Pancasila": [
      "Bab 1: Mengenal Lingkungan Sekitar",
      "Bab 2: Aku Anak yang Disiplin",
      "Bab 3: Kerja Sama di Lingkunganku",
      "Bab 4: Pancasila dalam Diriku",
    ],
    "Bahasa Indonesia": [
      "Bab 1: Sudah Besar",
      "Bab 2: Di Bawah Atap",
      "Bab 3: Lihat Sekitar",
      "Bab 4: Meliuk dan Menerjang",
      "Bab 5: Bertukar atau Membayar",
      "Bab 6: Satu Titik",
      "Bab 7: Asal-Usul",
      "Bab 8: Sehatlah Ragaku",
    ],
    Matematika: [
      "Bab 1: Bilangan Cacah sampai 10.000",
      "Bab 2: Pecahan",
      "Bab 3: Pola Gambar dan Pola Bilangan",
      "Bab 4: Pengukuran Luas dan Volume",
      "Bab 5: Bangun Datar",
      "Bab 6: Piktogram dan Diagram Batang",
    ],
    [IPAS]: [
      "Bab 1: Tumbuhan, Sumber Kehidupan di Bumi",
      "Bab 2: Wujud Zat dan Perubahannya",
      "Bab 3: Gaya di Sekitar Kita",
      "Bab 4: Mengubah Bentuk Energi",
      "Bab 5: Cerita Tentang Daerahku",
      "Bab 6: Indonesiaku Kaya Budaya",
      "Bab 7: Bagaimana Mendapatkan Semua Keperluan Kita?",
      "Bab 8: Membangun Masyarakat yang Beradab",
    ],
    [PJOK]: [
      "Bab 1: Aktivitas Variasi dan Kombinasi Pola Gerak Dasar Lokomotor",
      "Bab 2: Aktivitas Variasi dan Kombinasi Pola Gerak Dasar Non-Lokomotor",
      "Bab 3: Aktivitas Variasi dan Kombinasi Pola Gerak Dasar Manipulatif",
      "Bab 4: Aktivitas Senam",
      "Bab 5: Aktivitas Gerak Berirama",
      "Bab 6: Aktivitas Permainan dan Olahraga di Air",
      "Bab 7: Aktivitas Kebugaran yang Berkaitan dengan Kesehatan",
      "Bab 8: Kebersihan dan Kesehatan Alat Reproduksi",
    ],
    "Bahasa Inggris": [
      "Unit 1: What Are You Doing?",
      "Unit 2: There Are 67 English Books",
      "Unit 3: My Living Room is Beside The Kitchen",
      "Unit 4: Cici Cooks in The Kitchen",
      "Unit 5: Where is My Pencil?",
      "Unit 6: The Stove is in The Kitchen",
      "Unit 7: I Can Make Fried Egg in The Kitchen",
      "Unit 8: Be On Time!",
      "Unit 9: I Go to School after Having Breakfast",
      "Unit 10: He Always Gets Up at 5 O’clock",
      "Unit 11: How Do You Go to School?",
      "Unit 12: He Goes to School by Bike",
    ],
  },
  "5 SD": {
    [PAI]: [
      "Bab 1: Menyayangi Anak Yatim",
      "Bab 2: Lebih Dekat dengan Nama-nama Allah",
      "Bab 3: Aku Anak Saleh",
      "Bab 4: Hidup Lapang dengan Berbagi",
      "Bab 5: Meneladan Perjuangan Rasulullah",
      "Bab 6: Hidup Damai Dalam Kebersamaan",
      "Bab 7: Ketika Kehidupan Telah Berhenti",
      "Bab 8: Senangnya Berteman",
      "Bab 9: Ibadah Haji dan Kurban",
      "Bab 10: Keteladanan Khulafaur Rasyidin",
    ],
    "Pendidikan Pancasila": [
      "Bab 1: Pancasila dalam Kehidupanku",
      "Bab 2: Norma dalam Kehidupanku",
      "Bab 3: Keragaman Budaya Indonesiaku",
      "Bab 4: Aku dan Lingkungan Sekitarku",
    ],
    "Bahasa Indonesia": [
      "Bab 1: Aku yang Unik",
      "Bab 2: Buku Jendela Dunia",
      "Bab 3: Ekspresi Diri Melalui Hobi",
      "Bab 4: Belajar Berwirausaha",
      "Bab 5: Cinta Indonesia",
      "Bab 6: Sayangi Bumi",
    ],
    Matematika: [
      "Bab 1: Bilangan Cacah Sampai 100.000",
      "Bab 2: KPK dan FPB",
      "Bab 3: Bilangan Pecahan",
      "Bab 4: Keliling Bangun Datar",
      "Bab 5: Luas Daerah Bangun Datar",
      "Bab 6: Sudut",
      "Bab 7: Membandingkan Ciri-Ciri Bangun Datar",
      "Bab 8: Data",
      "Bab 9: Bilangan Cacah Sampai 1.000.000",
    ],
    [IPAS]: [
      "Bab 1: Di Mana Indonesia Berada?",
      "Bab 2: Majulah Daerahku!",
      "Bab 3: Harmoni dalam Ekosistem",
      "Bab 4: Air Sumber Kehidupan",
      "Bab 5: Daerahku yang Bersejarah",
      "Bab 6: Perubahan pada Diriku",
      "Bab 7: Bermain dengan Cahaya",
      "Bab 8: Ramai karena Bunyi",
    ],
    [PJOK]: [
      "Bab 1: Permainan dan Olahraga Bola Besar",
      "Bab 2: Permainan dan Olahraga Bola Kecil",
      "Bab 3: Atletik",
      "Bab 4: Senam",
      "Bab 5: Gerak Berirama",
      "Bab 6: Aktivitas Air",
      "Bab 7: Kebugaran Jasmani",
      "Bab 8: Kesehatan dan Pola Hidup Sehat",
    ],
    Informatika: [
      "Bab 1: Berpikir Komputasional",
      "Bab 2: Teknologi Informasi dan Komunikasi",
      "Bab 3: Data dan Informasi",
      "Bab 4: Algoritma Sederhana",
      "Bab 5: Keamanan Digital",
    ],
  },
  "6 SD": {
    [PAI]: [
      "Bab 1: Belajar Al-Qur’an dan Hadis",
      "Bab 2: Allah Swt. Maha Segalanya",
      "Bab 3: Hidup Damai dengan Saling Memaafkan",
      "Bab 4: Hukum Halal dan Haram",
      "Bab 5: Jasa Khulafaurrasyidin untuk Dunia",
      "Bab 6: Mengaji Surah Al-A‘la",
      "Bab 7: Indahnya Ketetapan Allah",
      "Bab 8: Peduli Lingkungan",
    ],
    "Pendidikan Pancasila": [
      "Bab 1: Belajar Pancasila dengan Menyenangkan",
      "Bab 2: Mengamalkan Pancasila untuk Kebahagiaan Bersama",
      "Bab 3: Mengenal Norma, Hak, dan Kewajiban dalam Kehidupan Berbangsa dan Bernegara",
      "Bab 4: Belajar Bermusyawarah",
      "Bab 5: Menghormati Perbedaan Budaya dan Agama dalam Kehidupan Sehari-hari",
      "Bab 6: Provinsiku Bagian dari Wilayah Negara Kesatuan Republik Indonesia",
    ],
    "Bahasa Indonesia": [
      "Bab 1: Bangga Menjadi Anak Indonesia",
      "Bab 2: Musisi Indonesia di Pentas Dunia",
      "Bab 3: Taman Nasional dan Situs Warisan Dunia",
      "Bab 4: Jeda untuk Iklim",
      "Bab 5: Anak-Anak yang Mengubah Dunia",
      "Bab 6: Liburan Perpisahan Kelas",
      "Bab 7: Aku Bisa Berempati",
      "Bab 8: Aman di Dunia Maya",
    ],
    Matematika: [
      "Bab 1: Pecahan dan Desimal",
      "Bab 2: Rasio",
      "Bab 3: Kubus dan Balok",
      "Bab 4: Peluang",
    ],
    [IPAS]: [
      "Bab 1: Bagaimana Tubuh Kita Bergerak?",
      "Bab 2: Cerita tentang Indonesia Kita",
      "Bab 3: Pelesir Keliling Dunia",
      "Bab 4: Indonesia dan Masyarakat Dunia",
      "Bab 5: Menjelajahi Bumi dan Antariksa",
      "Bab 6: Gawat! Benarkah Energi di Bumi akan Habis?",
      "Bab 7: Bumi Kita Terancam Bahaya",
      "Bab 8: Proyek Akhir IPAS",
    ],
    "Bahasa Inggris": [
      "Unit 1: I studied last night but my sister didn’t",
      "Unit 2: We went to the museum last week",
      "Unit 3: I was in Bali last week",
      "Unit 4: How did Cici feel yesterday?",
      "Unit 5: What did you do yesterday?",
      "Unit 6: My friend’s experience",
      "Unit 7: I will go to Bromo",
      "Unit 8: I will go to Dufan",
      "Unit 9: I will study at Junior High School next year",
      "Unit 10: I want to be a pilot",
      "Unit 11: My dream",
    ],
    [PJOK]: [
      "Bab 1: Permainan Bola Besar",
      "Bab 2: Permainan Bola Kecil",
      "Bab 3: Atletik",
      "Bab 4: Senam",
      "Bab 5: Aktivitas Ritmik",
      "Bab 6: Aktivitas Air",
      "Bab 7: Kebugaran Jasmani",
      "Bab 8: Kesehatan dan Pertolongan Pertama",
    ],
  },
  "7 SMP": {
    [PAI]: [
      "Bab 1: Al-Qur'an dan Sunah Sebagai Pedoman Hidup",
      "Bab 2: Meneladan Nama dan Sifat Allah untuk Kebaikan Hidup",
      "Bab 3: Menghadirkan Salat dan Zikir dalam Kehidupan",
      "Bab 4: Mengagungkan Allah SWT. dengan Tunduk Pada Perintah-Nya",
      "Bab 5: Damaskus: Pusat Peradaban Timur Islam (661-750 M)",
      "Bab 6: Alam Semesta Sebagai Tanda Kekuasaan Allah SWT.",
      "Bab 7: Mawas Diri dan Intropeksi Dalam Menjalani Kehidupan",
      "Bab 8: Menghindari Gibah dan Melaksanakan Tabayun",
      "Bab 9: Rukhsah: Kemudahan Dari Allah SWT dalam Beribadah Kepada-Nya",
      "Bab 10: Andalusia: Kota Peradaban Islam di Barat (756-1031 M)",
    ],
    "Pendidikan Agama Katolik dan Budi Pekerti": [
      "Bab 1: Manusia Sebagai Citra Allah",
      "Bab 2: Kemampuan Dan Keterbatasanku",
      "Bab 3: Manusia Berkembang Berkat Peran Sesama",
      "Bab 4: Yesus Teladan Hidupku",
      "Bab 5: Nilai-Nilai Dasar Hidup Bersama",
    ],
    "Pendidikan Pancasila": [
      "Bab 1: Pancasila sebagai Dasar Negara",
      "Bab 2: Undang-Undang Dasar Negara Republik Indonesia Tahun 1945",
      "Bab 3: Bhinneka Tunggal Ika",
      "Bab 4: Negara Kesatuan Republik Indonesia",
    ],
    "Bahasa Indonesia": [
      "Bab 1: Jelajah Nusantara",
      "Bab 2: Berkelana di Dunia Imajinasi",
      "Bab 3: Hal yang Baik bagi Tubuh",
      "Bab 4: Aksi Nyata Para Pelindung Bumi",
      "Bab 5: Membuka Gerbang Dunia",
      "Bab 6: Sampaikan Melalui Surat",
    ],
    Matematika: [
      "Bab 1: Bilangan Bulat",
      "Bab 2: Bilangan Rasional",
      "Bab 3: Rasio",
      "Bab 4: Bentuk Aljabar",
      "Bab 5: Kesebangunan",
      "Bab 6: Data dan Diagram",
    ],
    "Ilmu Pengetahuan Alam": [
      "Bab 1: Hakikat Ilmu Sains dan Metode Ilmiah",
      "Bab 2: Zat dan Perubahannya",
      "Bab 3: Suhu, Kalor, dan Pemuaian",
      "Bab 4: Gerak dan Gaya",
      "Bab 5: Klasifikasi Makhluk Hidup",
      "Bab 6: Ekologi dan Keanekaragaman Hayati Indonesia",
      "Bab 7: Bumi dan Tata Surya",
    ],
    "Ilmu Pengetahuan Sosial": [
      "Tema I: Kehidupan Sosial dan Kondisi Lingkungan Sekitar",
      "Tema II: Keberagaman Lingkungan Sekitar",
      "Tema III: Potensi Ekonomi Lingkungan",
      "Tema IV: Pemberdayaan Masyarakat",
    ],
    "Bahasa Inggris": [
      "Chapter 1: About Me",
      "Chapter 2: Culinary and Me",
      "Chapter 3: Home Sweet Home",
      "Chapter 4: My School Activities",
      "Chapter 5: This is My School",
    ],
    Informatika: [
      "Bab 1: Informatika dan Keterampilan Generik",
      "Bab 2: Berpikir Komputasional",
      "Bab 3: Teknologi Informasi dan Komunikasi",
      "Bab 4: Sistem Komputer",
      "Bab 5: Jaringan Komputer dan Internet",
      "Bab 6: Analisis Data",
      "Bab 7: Algoritma dan Pemrograman",
      "Bab 8: Dampak Sosial Informatika",
      "Bab 9: Praktika Lintas Bidang Informatika",
    ],
    [PJOK]: [
      "Bab 1: Permainan Bola Besar",
      "Bab 2: Permainan Bola Kecil",
      "Bab 3: Atletik",
      "Bab 4: Senam",
      "Bab 5: Gerak Berirama",
      "Bab 6: Aktivitas Air",
      "Bab 7: Kebugaran Jasmani",
      "Bab 8: Kesehatan Remaja",
    ],
  },
  "8 SMP": {
    [PAI]: [
      "Bab 1: Inspirasi Al-Qur’an: Melestarikan Alam, Menjaga Kehidupan",
      "Bab 2: Meyakini Kitab-Kitab Allah: Menjadi Generasi Pecinta Al-Qur’an yang Toleran",
      "Bab 3: Menjadi Pribadi Berintegritas dengan Sifat Amanah dan Jujur",
      "Bab 4: Ibadah dengan Disiplin dan Penuh Harap Kepada Allah Swt serta Peduli terhadap Sesama Melalui Salat Gerhana, Istiska, dan Jenazah",
      "Bab 5: Meneladani Produktivitas dalam Berkarya dan Semangat Literasi Masa Keemasan Islam Era Daulah Abbasiyah (750-1258 M)",
      "Bab 6: Inspirasi Al-Qur’an: Indahnya Beragama Secara Moderat",
      "Bab 7: Meyakini Nabi dan Rasul Allah: Menjadi Generasi Digital yang Berkarakter",
      "Bab 8: Menjadi Generasi Toleran Membangun Harmoni Intern dan Antar Umat Beragama",
      "Bab 9: Menjadi Pribadi yang Dapat Dipercaya serta Terhindar dari Riba dalam Jual Beli dan Hutang Piutang",
      "Bab 10: Meneladani Inspirasi dan Kontribusi Ilmuwan Muslim Pada Masa Bani Abbasiyah untuk Kemanusiaan dan Peradaban",
    ],
    "Pendidikan Pancasila": [
      "Bab 1: Pancasila sebagai Ideologi dan Dasar Negara",
      "Bab 2: Undang-Undang Dasar Negara Republik Indonesia Tahun 1945",
      "Bab 3: Kebinekaan dalam Bingkai Bhinneka Tunggal Ika",
      "Bab 4: Negara Kesatuan Republik Indonesia",
    ],
    "Bahasa Indonesia": [
      "Bab 1: Menulis Teks Laporan Hasil Observasi",
      "Bab 2: Membuat Iklan, Slogan, dan Poster",
      "Bab 3: Menulis Artikel Ilmiah Populer",
      "Bab 4: Mengulas Karya Fiksi",
      "Bab 5: Menciptakan Puisi",
      "Bab 6: Menulis Teks Pidato",
    ],
    Matematika: [
      "Bab 1: Bilangan Berpangkat",
      "Bab 2: Teorema Pythagoras",
      "Bab 3: Persamaan Linear dan Pertidaksamaan Linear Satu Variabel",
      "Bab 4: Relasi dan Fungsi",
      "Bab 5: Persamaan Garis Lurus",
      "Bab 6: Statistika",
    ],
    "Ilmu Pengetahuan Alam": [
      "Bab 1: Struktur dan Fungsi Tubuh Makhluk Hidup (Bagian I): Sistem Pencernaan dan Peredaran Darah",
      "Bab 2: Struktur dan Fungsi Tubuh Makhluk Hidup (Bagian II): Sistem Pernapasan dan Ekskresi",
      "Bab 3: Memanfaatkan Usaha, Energi, dan Pesawat Sederhana",
      "Bab 4: Teknologi Penerapan Tekanan pada Zat",
      "Bab 5: Manfaat Gelombang dan Cahaya bagi Manusia",
      "Bab 6: Pemisahan Campuran di Sekitar Kita",
      "Bab 7: Tanah bagi Kehidupan Berkelanjutan",
    ],
    "Ilmu Pengetahuan Sosial": [
      "Tema 01: Kondisi Geografis dan Pelestarian Sumber Daya Alam",
      "Tema 02: Kemajemukan Masyarakat Indonesia",
      "Tema 03: Nasionalisme dan Jati Diri Bangsa",
      "Tema 04: Pembangunan Perekonomian Indonesia",
    ],
    "Bahasa Inggris": [
      "Chapter 1: Celebrating Independence Day",
      "Chapter 2: Kindness Begins with Me",
      "Chapter 3: Love Our World",
      "Chapter 4: No Littering",
      "Chapter 5: Embrace Yourself",
    ],
    Informatika: [
      "Bab 1: Analisis Data",
      "Bab 2: Berpikir Komputasional",
      "Bab 3: Algoritma Pemrograman",
      "Bab 4: Jejak Bermedia Digital",
      "Bab 5: Pemanfaatan Perangkat Digital",
    ],
  },
  "9 SMP": {
    [PAI]: [
      "Bab 1: Al-Qur’an Menginspirasi: Meraih Kesuksesan dengan Semangat Mencari Ilmu",
      "Bab 2: Meyakini Hari Akhir dengan Mawas Diri",
      "Bab 3: Indahnya Etika Pergaulan dan Komunikasi Islami",
      "Bab 4: Bersyukur Dengan Akikah Peduli Sesama dengan Berkurban",
      "Bab 5: Mengapresiasi Peradaban Daulah Usmani",
      "Bab 6: Al-Qur’an Menginspirasi: Menjadi Khalifatullah Fil‘ard Penebar Kasih Sayang",
      "Bab 7: Meraih Ketenangan Jiwa dengan Meyakini Qada dan Qadar",
      "Bab 8: Dengan Seni Islami, Kehidupan Semakin Harmoni",
      "Bab 9: Mengenal Imam Madzhab, Ibadah Semakin Mantab",
      "Bab 10: Mengapresiasi Peradaban Pada Masa Syafawi dan India Mughal",
    ],
    "Pendidikan Pancasila": [
      "Bab 1: Pancasila dalam Kehidupan Berbangsa dan Bernegara",
      "Bab 2: Hak dan Kewajiban Warga Negara",
      "Bab 3: Persatuan dalam Keberagaman",
      "Bab 4: Bela Negara dan Ketahanan Nasional",
    ],
    "Bahasa Indonesia": [
      "Bab 1: Demi Keluarga",
      "Bab 2: Buku-Buku Berbicara",
      "Bab 3: Komunikasi Ujung Jari",
      "Bab 4: Dari Hobi Menjadi Pundi-Pundi",
      "Bab 5: Menuju Laut",
      "Bab 6: Merencanakan Masa Depan",
    ],
    Matematika: [
      "Bab 1: Sistem Persamaan Linear Dua Variabel",
      "Bab 2: Bangun Ruang",
      "Bab 3: Transformasi Geometri",
      "Bab 4: Peluang dan Pemilihan Sampel",
    ],
    "Ilmu Pengetahuan Alam": [
      "Bab 1: Sistem Koordinasi dan Homeostasis Tubuh Manusia",
      "Bab 2: Zat Aditif dan Zat Adiktif",
      "Bab 3: Sistem Reproduksi Manusia",
      "Bab 4: Pewarisan Sifat dan Bioteknologi",
      "Bab 5: Listrik, Magnet, dan Energi Alternatif",
      "Bab 6: Isu-Isu Lingkungan",
    ],
    "Ilmu Pengetahuan Sosial": [
      "Tema 01: Manusia dan Perubahan",
      "Tema 02: Perkembangan Ekonomi Digital",
      "Tema 03: Tantangan Pembangunan Indonesia",
      "Tema 04: Kerja Sama Dunia",
    ],
    "Bahasa Inggris": [
      "Chapter 1: Exploring Fauna of Indonesia",
      "Chapter 2: Taking Trips",
      "Chapter 3: Journey to Fantasy Worlds",
      "Chapter 4: Upcycling Used Materials",
      "Chapter 5: Digital Life",
    ],
    Informatika: [
      "Bab 1: Informatika SMP",
      "Bab 2: Berpikir Komputasional",
      "Bab 3: Teknologi Informasi dan Komunikasi",
      "Bab 4: Sistem Komputer",
      "Bab 5: Jaringan Komputer dan Internet",
      "Bab 6: Analisis Data",
      "Bab 7: Algoritma dan Pemrograman",
      "Bab 8: Dampak Sosial Informatika",
      "Bab 9: Praktik Lintas Bidang Informatika",
    ],
  },
  "10 SMA": {
    [PAI]: [
      "Bab 1: Meraih Kesuksesan dengan Optimis, Ikhtiar, dan Tawakal",
      "Bab 2: Memahami Hakikat dan Mewujudkan Ketauhidan dengan Syu'abul Iman",
      "Bab 3: Menjalani Hidup Penuh Manfaat dengan Menghindari Berfoya-foya dan Takabur",
      "Bab 4: Menjauhi Pergaulan Bebas dan Perbuatan Zina",
      "Bab 5: Menyembah Allah Swt. sebagai Ibadah yang Tulus",
      "Bab 6: Meneladani Jejak Langkah Rasulullah saw. di Mekah",
      "Bab 7: Dakwah Rasulullah saw. di Madinah",
      "Bab 8: Menjaga Martabat Manusia dengan Menunaikan Hak Asasi",
      "Bab 9: Pengurusan Jenazah",
      "Bab 10: Peradaban Islam pada Masa Khulafaur Rasyidin",
    ],
    "Pendidikan Pancasila": [
      "Bab 1: Pancasila sebagai Dasar Negara dan Ideologi Bangsa",
      "Bab 2: Identitas Nasional dan Konstitusi",
      "Bab 3: Hak Asasi Manusia",
      "Bab 4: Demokrasi dan Keadilan Sosial",
    ],
    "Bahasa Indonesia": [
      "Bab 1: Mengungkap Fakta Alam Secara Objektif",
      "Bab 2: Mengungkapkan Kritik Lewat Humor",
      "Bab 3: Menyusuri Kisah Lintas Zaman",
      "Bab 4: Belajar Menjadi Negosiator Ulung",
      "Bab 5: Memetik Keteladanan dari Biografi Tokoh Inspiratif",
      "Bab 6: Berkarya dan Berekspresi Melalui Puisi",
    ],
    Matematika: [
      "Bab 1: Eksponen dan Logaritma",
      "Bab 2: Barisan dan Deret",
      "Bab 3: Vektor",
      "Bab 4: Trigonometri",
      "Bab 5: Sistem Persamaan dan Pertidaksamaan Linear",
      "Bab 6: Fungsi Kuadrat",
      "Bab 7: Statistika",
      "Bab 8: Peluang",
    ],
    "Bahasa Inggris": [
      "Unit 1: Great Athletes",
      "Unit 2: Sports Events",
      "Unit 3: Historical Recount",
      "Unit 4: Narrative Legends",
      "Unit 5: Procedure Text",
      "Unit 6: Explanation Text",
    ],
    Sejarah: [
      "Bab 1: Manusia dan Sejarah",
      "Bab 2: Penelitian Sejarah",
      "Bab 3: Indonesia pada Masa Praaksara",
      "Bab 4: Kerajaan Hindu-Buddha",
      "Bab 5: Kerajaan Islam di Indonesia",
      "Bab 6: Kolonialisme dan Perlawanan",
    ],
    Informatika: [
      "Bab 1: Informatika dan Keterampilan Generik",
      "Bab 2: Berpikir Komputasional",
      "Bab 3: Teknologi Informasi dan Komunikasi",
      "Bab 4: Sistem Komputer",
      "Bab 5: Jaringan Komputer dan Internet",
      "Bab 6: Analisis Data",
      "Bab 7: Algoritma dan Pemrograman",
      "Bab 8: Dampak Sosial Informatika",
    ],
    "Ilmu Pengetahuan Alam": [
      "Bab 1: Pengukuran dalam Kerja Ilmiah",
      "Bab 2: Virus dan Peranannya",
      "Bab 3: Kimia Hijau dalam Pembangunan Berkelanjutan 2030",
      "Bab 4: Hukum Dasar Kimia di Sekitar Kita",
      "Bab 5: Struktur Atom – Keunggulan Nanomaterial",
      "Bab 6: Energi Terbarukan",
      "Bab 7: Keanekaragaman Makhluk Hidup, Interaksi, dan Peranannya di Alam",
      "Bab 8: Pemanasan Global: Konsep dan Solusi",
    ],
    Fisika: [
      "Bab 1: Pengukuran",
      "Bab 2: Vektor",
      "Bab 3: Gerak Lurus",
      "Bab 4: Gerak Parabola dan Melingkar",
      "Bab 5: Hukum Newton",
      "Bab 6: Usaha dan Energi",
      "Bab 7: Momentum dan Impuls",
      "Bab 8: Getaran Harmonis",
    ],
    Kimia: [
      "Bab 1: Hakikat Ilmu Kimia dan Metode Ilmiah",
      "Bab 2: Struktur Atom",
      "Bab 3: Sistem Periodik Unsur",
      "Bab 4: Ikatan Kimia",
      "Bab 5: Stoikiometri",
      "Bab 6: Larutan Elektrolit dan Redoks",
    ],
    Biologi: [
      "Bab 1: Keanekaragaman Hayati",
      "Bab 2: Virus",
      "Bab 3: Klasifikasi Makhluk Hidup",
      "Bab 4: Ekologi",
      "Bab 5: Perubahan Lingkungan",
    ],
    Ekonomi: [
      "Bab 1: Konsep Dasar Ilmu Ekonomi",
      "Bab 2: Masalah Pokok Ekonomi",
      "Bab 3: Kegiatan Ekonomi",
      "Bab 4: Permintaan, Penawaran, dan Harga Keseimbangan",
      "Bab 5: Pasar",
      "Bab 6: Uang dan Lembaga Keuangan",
    ],
    Geografi: [
      "Bab 1: Pengetahuan Dasar Geografi",
      "Bab 2: Peta dan Penginderaan Jauh",
      "Bab 3: Dinamika Litosfer",
      "Bab 4: Atmosfer",
      "Bab 5: Hidrosfer",
    ],
    Sosiologi: [
      "Bab 1: Sosiologi sebagai Ilmu tentang Masyarakat",
      "Bab 2: Hubungan Sosial",
      "Bab 3: Interaksi Sosial",
      "Bab 4: Sosialisasi dan Pembentukan Kepribadian",
      "Bab 5: Perilaku Menyimpang dan Pengendalian Sosial",
    ],
  },
  "11 SMA": {
    [PAI]: [
      "Bab 1: Membiasakan Berpikir Kritis dan Semangat Mencintai Iptek",
      "Bab 2: Bukti Beriman: Memenuhi Janji, Mensyukuri Nikmat, Memelihara Lisan, Menutupi Aib Orang Lain",
      "Bab 3: Menghindari Perkelahian Pelajar, Minuman Keras, dan Narkoba",
      "Bab 4: Menebarkan Islam dengan Santun dan Damai Melalui Dakwah, Khutbah, dan Tablig",
      "Bab 5: Meneladani Jejak Langkah Ulama Indonesia yang Mendunia",
      "Bab 6: Menguatkan Kerukunan melalui Toleransi dan Memelihara Kehidupan Manusia",
      "Bab 7: Menguatkan Iman dengan Menjaga Kehormatan, Ikhlas, Malu, dan Zuhud",
      "Bab 8: Adab Menggunakan Media Sosial",
      "Bab 9: Ketentuan Pernikahan dalam Islam",
      "Bab 10: Peradaban Islam pada Masa Modern",
    ],
    "Pendidikan Pancasila": [
      "Bab 1: Menjiwai Pancasila",
      "Bab 2: Demokrasi Berdasarkan UUD NRI Tahun 1945",
      "Bab 3: Harmoni dalam Keberagaman",
      "Bab 4: Menjaga Keutuhan NKRI",
    ],
    "Bahasa Indonesia": [
      "Bab 1: Mengenalkan Produk Pangan Lokal Indonesia",
      "Bab 2: Menyajikan Berita Inovasi yang Menghibur",
      "Bab 3: Menggali Nilai Sejarah Bangsa Melalui Cerita Pendek",
      "Bab 4: Menulis Puisi Bertema Kesempatan untuk Semua",
      "Bab 5: Mengenal Indonesia melalui Pertunjukan Drama",
      "Bab 6: Berperan dalam Konservasi Alam Indonesia melalui Karya Ilmiah",
    ],
    Matematika: [
      "Bab 1: Komposisi Fungsi dan Fungsi Invers",
      "Bab 2: Lingkaran",
      "Bab 3: Statistika",
      "Bab 4: Peluang",
      "Bab 5: Limit Fungsi Aljabar",
      "Bab 6: Turunan Fungsi Aljabar",
    ],
    "Matematika Lanjutan": [
      "Bab 1: Program Linear",
      "Bab 2: Matriks",
      "Bab 3: Transformasi Geometri",
      "Bab 4: Barisan dan Deret",
      "Bab 5: Limit dan Turunan",
      "Bab 6: Integral",
    ],
    Kimia: [
      "Bab 1: Struktur Atom dan Sistem Periodik Unsur",
      "Bab 2: Ikatan Kimia",
      "Bab 3: Stoikiometri",
      "Bab 4: Hidrokarbon",
      "Bab 5: Termokimia",
      "Bab 6: Kinetika Kimia",
      "Bab 7: Kesetimbangan Kimia",
    ],
    Geografi: [
      "Bab 1: Posisi Strategis Indonesia dan Potensi Sumber Daya Alam",
      "Bab 2: Keragaman Hayati",
      "Bab 3: Lingkungan Hidup dan Kependudukan",
      "Bab 4: Mitigasi dan Adaptasi Kebencanaan",
    ],
    Informatika: [
      "Bab 1: Tentang Informatika",
      "Bab 2: Strategi Algoritmik dan Pemrograman",
      "Bab 3: Berpikir Kritis dan Dampak Sosial Informatika",
      "Bab 4: Jaringan Komputer dan Internet",
      "Bab 5: Pengembangan Aplikasi Mobile dengan Library Kecerdasan Artifisial",
      "Bab 6: Proyek Analisis Data: “Hutanku Dulu, Kini, dan yang Akan Datang”",
    ],
    Fisika: [
      "Bab 1: Dinamika Rotasi dan Kesetimbangan Benda Tegar",
      "Bab 2: Elastisitas dan Hukum Hooke",
      "Bab 3: Fluida Statis dan Dinamis",
      "Bab 4: Teori Kinetik Gas",
      "Bab 5: Suhu, Kalor, dan Teori Kinetik Gas",
      "Bab 6: Gelombang Mekanik",
      "Bab 7: Gelombang Berjalan dan Stasioner",
      "Bab 8: Alat Optik",
    ],
    Biologi: [
      "Bab 1: Sel",
      "Bab 2: Pergerakan Zat melalui Membran",
      "Bab 3: Sistem Gerak pada Manusia",
      "Bab 4: Sistem Peredaran Darah",
      "Bab 5: Sistem Pencernaan",
      "Bab 6: Sistem Pernapasan",
      "Bab 7: Sistem Ekskresi",
      "Bab 8: Sistem Koordinasi",
    ],
    Ekonomi: [
      "Bab 1: Pendapatan Nasional",
      "Bab 2: Pertumbuhan dan Pembangunan Ekonomi",
      "Bab 3: Ketenagakerjaan",
      "Bab 4: APBN dan APBD",
      "Bab 5: Pajak",
      "Bab 6: Kebijakan Moneter dan Fiskal",
    ],
    Sosiologi: [
      "Bab 1: Kelompok Sosial",
      "Bab 2: Permasalahan Sosial",
      "Bab 3: Perbedaan, Kesetaraan, dan Harmoni Sosial",
      "Bab 4: Konflik, Kekerasan, dan Perdamaian",
      "Bab 5: Integrasi Sosial",
    ],
    Sejarah: [
      "Bab 1: Kolonialisme dan Imperialisme di Indonesia",
      "Bab 2: Pergerakan Kebangsaan Indonesia",
      "Bab 3: Pendudukan Jepang",
      "Bab 4: Proklamasi dan Revolusi Kemerdekaan",
    ],
    Antropologi: [
      "Bab 1: Antropologi sebagai Ilmu",
      "Bab 2: Kebudayaan",
      "Bab 3: Identitas dan Jati Diri",
      "Bab 4: Keragaman Budaya Indonesia",
    ],
  },
  "12 SMA": {
    [PAI]: [
      "Bab 1: Sabar Dalam Menghadapi Musibah Dan Ujian",
      "Bab 2: Indahnya Kehidupan Bermakna",
      "Bab 3: Munafik dan Keras Hati Tak Akan Pernah Maju",
      "Bab 4: Kewarisan dan Kearifan dalam Islam",
      "Bab 5: Perkembangan Peradaban Islam di Dunia",
      "Bab 6: Cinta Tanah Air dan Moderasi Beragama",
      "Bab 7: Ilmu Kalam",
      "Bab 8: Sikap Inovatif dan Etika dalam Berorganisasi",
      "Bab 9: Ijtihad",
      "Bab 10: Peran Organisasi Islam di Indonesia",
    ],
    "Pendidikan Pancasila": [
      "Bab 1: Ber-Pancasila dalam Keseharian di Masyarakat",
      "Bab 2: Ber-Pancasila dalam Kehidupan Global",
      "Bab 3: Kesadaran Warga Negara dalam Menghadapi Kasus Pelanggaran Hak dan Pengingkaran Kewajiban",
      "Bab 4: Generasi Solutif Mengatasi Pelanggaran Hak dan Pengingkaran Kewajiban",
      "Bab 5: Praktik Gotong Royong dalam Kehidupan Masyarakat Indonesia",
      "Bab 6: Menelusur Lembaga Negara",
      "Bab 7: Menjadi Pelopor Pemilih Pemula dalam Demokrasi Indonesia",
    ],
    "Bahasa Indonesia": [
      "Bab 1: Mengkritisi Informasi Tentang Tokoh",
      "Bab 2: Mempresentasikan Ide Kewirausahaan",
      "Bab 3: Memahami dan Mendiskusikan Fenomena Kecerdasan Buatan",
      "Bab 4: Menyampaikan Opini tentang Perundungan",
      "Bab 5: Mengungkapkan Kekaguman Dalam Narasi Kearifan Lokal",
      "Bab 6: Menulis Praktik Baik dan Cerita tentang Lingkungan",
    ],
    Matematika: [
      "Bab 1: Integral",
      "Bab 2: Geometri Ruang",
      "Bab 3: Statistika Inferensial",
      "Bab 4: Peluang Kejadian Majemuk",
      "Bab 5: Limit Fungsi Trigonometri",
    ],
    "Matematika Lanjutan": [
      "Bab 1: Integral Tentu dan Penerapannya",
      "Bab 2: Dimensi Tiga",
      "Bab 3: Statistika",
      "Bab 4: Peluang",
      "Bab 5: Matriks dan Transformasi",
    ],
    Sejarah: [
      "Bab 1: Perjuangan Mempertahankan Kemerdekaan",
      "Bab 2: Demokrasi Liberal hingga Masa Demokrasi Terpimpin (1950—1966)",
      "Bab 3: Indonesia Masa Orde Baru (1966—1998)",
      "Bab 4: Indonesia Masa Reformasi",
    ],
    Geografi: [
      "Bab 1: Pengembangan Wilayah, Tata Ruang, dan Pengaruhnya terhadap Kebahagiaan",
      "Bab 2: Pembangunan Wilayah, Revolusi Industri, dan Pengaruhnya terhadap Ruang Muka Bumi dan Kesejahteraan",
      "Bab 3: Dinamika Kerja Sama Antarnegara dan Pengaruhnya terhadap Ketahanan Wilayah Indonesia",
    ],
    Informatika: [
      "Bab 1: Informatika Sekarang dan Masa Depan",
      "Bab 2: Sistem Komputer",
      "Bab 3: Berpikir Komputasional dan Algoritma",
      "Bab 4: Jaringan Komputer dan Internet",
      "Bab 5: Dampak Sosial Informatika",
      "Bab 6: Praktik Lintas Bidang",
    ],
    Fisika: [
      "Bab 1: Listrik Statis",
      "Bab 2: Listrik Dinamis",
      "Bab 3: Medan Magnet",
      "Bab 4: Induksi Elektromagnetik",
      "Bab 5: Arus Bolak-Balik",
      "Bab 6: Gelombang Elektromagnetik",
      "Bab 7: Relativitas Khusus",
      "Bab 8: Radiasi Benda Hitam dan Dualisme Gelombang Partikel",
    ],
    Kimia: [
      "Bab 1: Sifat Koligatif Larutan",
      "Bab 2: Redoks dan Elektrokimia",
      "Bab 3: Kimia Unsur",
      "Bab 4: Senyawa Karbon",
      "Bab 5: Benzena dan Turunannya",
      "Bab 6: Biomolekul",
    ],
    Biologi: [
      "Bab 1: Pertumbuhan dan Perkembangan",
      "Bab 2: Enzim dan Metabolisme",
      "Bab 3: Genetika",
      "Bab 4: Pembelahan Sel",
      "Bab 5: Evolusi",
      "Bab 6: Bioteknologi",
    ],
    Ekonomi: [
      "Bab 1: Akuntansi sebagai Sistem Informasi",
      "Bab 2: Persamaan Dasar Akuntansi",
      "Bab 3: Siklus Akuntansi Perusahaan Jasa",
      "Bab 4: Siklus Akuntansi Perusahaan Dagang",
      "Bab 5: Manajemen",
      "Bab 6: Badan Usaha dan Koperasi",
    ],
    Sosiologi: [
      "Bab 1: Perubahan Sosial",
      "Bab 2: Globalisasi dan Masyarakat Digital",
      "Bab 3: Ketimpangan Sosial",
      "Bab 4: Kearifan Lokal dan Pemberdayaan Komunitas",
      "Bab 5: Penelitian Sosial",
    ],
  },
};

export function terapkanBabBukuSiswa(
  data: Record<string, Record<string, string[]>>,
): Record<string, Record<string, string[]>> {
  const hasil: Record<string, Record<string, string[]>> = {};

  for (const [kelas, mapel] of Object.entries(data)) {
    const overlay = BAB_BUKU_SISWA[kelas] ?? {};
    hasil[kelas] = { ...mapel };
    for (const [nama, bab] of Object.entries(overlay)) {
      if (nama in hasil[kelas]) hasil[kelas][nama] = [...bab];
    }
    const islam = overlay[PAI];
    if (islam && "Pendidikan Agama dan Budi Pekerti" in hasil[kelas]) {
      hasil[kelas]["Pendidikan Agama dan Budi Pekerti"] = [...islam];
    }
  }

  return hasil;
}
