export const OPSI_LAIN_NYA = "LAIN NYA (ketik manual)";

export const DATA_KURIKULUM: Record<string, Record<string, string[]>> = {
  "1 SD": {
    "Pendidikan Agama dan Budi Pekerti": [
      "Bab 1: Aku Cinta Tuhan",
      "Bab 2: Doa Sehari-hari",
      "Bab 3: Akhlak Terpuji",
      "Bab 4: Kisah Keteladanan",
    ],
    "Pendidikan Pancasila": [
      "Bab 1: Identitasku",
      "Bab 2: Aturan di Rumah dan Sekolah",
      "Bab 3: Gotong Royong",
      "Bab 4: Cinta Tanah Air",
    ],
    "Bahasa Indonesia": [
      "Bab 1: Aku dan Temanku",
      "Bab 2: Bermain di Rumah",
      "Bab 3: Kegiatan di Sekolah",
      "Bab 4: Aku Suka Membaca",
    ],
    Matematika: [
      "Bab 1: Bilangan sampai 20",
      "Bab 2: Penjumlahan dan Pengurangan",
      "Bab 3: Pengukuran Panjang dan Berat",
      "Bab 4: Bangun Datar",
      "Bab 5: Pola Bilangan",
    ],
    "Pendidikan Jasmani, Olahraga, dan Kesehatan": [
      "Bab 1: Gerak Dasar Lokomotor",
      "Bab 2: Permainan Sederhana",
      "Bab 3: Kesehatan Diri",
      "Bab 4: Kebugaran Jasmani",
    ],
    "Seni dan Budaya": [
      "Bab 1: Menggambar dan Mewarnai",
      "Bab 2: Menyanyi Lagu Anak",
      "Bab 3: Gerak dan Tari",
      "Bab 4: Kerajinan dari Bahan Alam",
    ],
    "Bahasa Inggris": [
      "Bab 1: Greetings",
      "Bab 2: Numbers and Colors",
      "Bab 3: Myself and My Family",
      "Bab 4: Animals around Me",
    ],
    "Muatan Lokal": [
      "Bab 1: Bahasa Daerah",
      "Bab 2: Budaya Setempat",
      "Bab 3: Kearifan Lokal",
    ],
  },
  "2 SD": {
    "Pendidikan Agama dan Budi Pekerti": [
      "Bab 1: Iman yang Tumbuh",
      "Bab 2: Ibadah Harian",
      "Bab 3: Saling Menghormati",
      "Bab 4: Peduli Sesama",
    ],
    "Pendidikan Pancasila": [
      "Bab 1: Keberagaman",
      "Bab 2: Kerja Sama",
      "Bab 3: Jujur dan Bertanggung Jawab",
      "Bab 4: Hidup Rukun",
    ],
    "Bahasa Indonesia": [
      "Bab 1: Mengenal Perasaan",
      "Bab 2: Cerita di Sekitarku",
      "Bab 3: Membaca Informasi",
      "Bab 4: Menulis Kalimat Sederhana",
    ],
    Matematika: [
      "Bab 1: Bilangan 1 sampai 100",
      "Bab 2: Operasi Hitung",
      "Bab 3: Pengukuran Waktu dan Uang",
      "Bab 4: Pola dan Bangun",
      "Bab 5: Data Sederhana",
    ],
    "Pendidikan Jasmani, Olahraga, dan Kesehatan": [
      "Bab 1: Gerak Dasar Manipulatif",
      "Bab 2: Permainan Berkelompok",
      "Bab 3: Kebersihan Diri",
      "Bab 4: Senam Irama",
    ],
    "Seni dan Budaya": [
      "Bab 1: Menggambar Bentuk",
      "Bab 2: Lagu Daerah",
      "Bab 3: Tari Sederhana",
      "Bab 4: Kolase dan Prakarya",
    ],
    "Bahasa Inggris": [
      "Bab 1: School Things",
      "Bab 2: Daily Activities",
      "Bab 3: Food and Drink",
      "Bab 4: My Home",
    ],
    "Muatan Lokal": [
      "Bab 1: Permainan Tradisional",
      "Bab 2: Makanan Khas Daerah",
      "Bab 3: Cerita Rakyat Setempat",
    ],
  },
  "3 SD": {
    "Pendidikan Agama dan Budi Pekerti": [
      "Bab 1: Mengenal Kitab Suci",
      "Bab 2: Ibadah dengan Khusyuk",
      "Bab 3: Jujur dan Amanah",
      "Bab 4: Hidup Bertetangga",
    ],
    "Pendidikan Pancasila": [
      "Bab 1: Hak dan Kewajiban",
      "Bab 2: Aturan di Masyarakat",
      "Bab 3: Simbol Pancasila",
      "Bab 4: Persatuan dalam Perbedaan",
    ],
    "Bahasa Indonesia": [
      "Bab 1: Ayo Main!",
      "Bab 2: Menyusun Kalimat",
      "Bab 3: Membaca Cerita",
      "Bab 4: Menulis Pengalaman",
    ],
    Matematika: [
      "Bab 1: Bilangan Cacah",
      "Bab 2: Perkalian dan Pembagian",
      "Bab 3: Pecahan Sederhana",
      "Bab 4: Keliling dan Luas",
      "Bab 5: Pengukuran",
    ],
    "Ilmu Pengetahuan Alam dan Sosial (IPAS)": [
      "Bab 1: Kenali Hewan dan Tanaman",
      "Bab 2: Wujud Benda",
      "Bab 3: Cuaca dan Musim",
      "Bab 4: Lingkungan Rumahku",
      "Bab 5: Arah dan Peta Sederhana",
    ],
    "Pendidikan Jasmani, Olahraga, dan Kesehatan": [
      "Bab 1: Gerak Dasar Kombinasi",
      "Bab 2: Permainan Bola",
      "Bab 3: Pola Hidup Sehat",
      "Bab 4: Aktivitas di Alam",
    ],
    "Seni dan Budaya": [
      "Bab 1: Menggambar Ilustrasi",
      "Bab 2: Ansambel Sederhana",
      "Bab 3: Tari Kreasi",
      "Bab 4: Kerajinan Tangan",
    ],
    "Bahasa Inggris": [
      "Bab 1: My Classroom",
      "Bab 2: Days and Time",
      "Bab 3: Weather",
      "Bab 4: Hobbies",
    ],
    "Muatan Lokal": [
      "Bab 1: Sejarah Desa/Kota",
      "Bab 2: Tokoh Daerah",
      "Bab 3: Adat Istiadat",
    ],
  },
  "4 SD": {
    "Pendidikan Agama dan Budi Pekerti": [
      "Bab 1: Nilai Keimanan",
      "Bab 2: Ibadah Sosial",
      "Bab 3: Toleransi",
      "Bab 4: Menjaga Alam Ciptaan",
    ],
    "Pendidikan Pancasila": [
      "Bab 1: Norma dan Aturan",
      "Bab 2: Musyawarah",
      "Bab 3: Keberagaman Budaya Indonesia",
      "Bab 4: Cinta Tanah Air",
    ],
    "Bahasa Indonesia": [
      "Bab 1: Gagasan Utama",
      "Bab 2: Teks Narasi",
      "Bab 3: Teks Informasi",
      "Bab 4: Surat dan Pengumuman",
    ],
    Matematika: [
      "Bab 1: Pecahan Desimal",
      "Bab 2: KPK dan FPB",
      "Bab 3: Bangun Datar",
      "Bab 4: Data dan Diagram",
      "Bab 5: Sudut dan Pengukuran",
    ],
    "Ilmu Pengetahuan Alam dan Sosial (IPAS)": [
      "Bab 1: Tumbuhan Sumber Kehidupan",
      "Bab 2: Gaya dan Gerak",
      "Bab 3: Wujud Zat dan Perubahannya",
      "Bab 4: Peta dan Lingkungan",
      "Bab 5: Keanekaragaman Hayati Indonesia",
    ],
    "Pendidikan Jasmani, Olahraga, dan Kesehatan": [
      "Bab 1: Permainan Bola Besar",
      "Bab 2: Atletik Dasar",
      "Bab 3: Senam Lantai",
      "Bab 4: Kesehatan dan Gizi",
    ],
    "Seni dan Budaya": [
      "Bab 1: Motif Nusantara",
      "Bab 2: Lagu Wajib dan Daerah",
      "Bab 3: Tari Tradisional",
      "Bab 4: Karya Dua dan Tiga Dimensi",
    ],
    "Bahasa Inggris": [
      "Bab 1: Describing People",
      "Bab 2: Places around Town",
      "Bab 3: Daily Routines",
      "Bab 4: Simple Instructions",
    ],
    "Muatan Lokal": [
      "Bab 1: Potensi Daerah",
      "Bab 2: Kerajinan Lokal",
      "Bab 3: Lingkungan Budaya",
    ],
  },
  "5 SD": {
    "Pendidikan Agama dan Budi Pekerti": [
      "Bab 1: Iman dan Ilmu",
      "Bab 2: Ibadah dengan Kesungguhan",
      "Bab 3: Akhlak kepada Sesama",
      "Bab 4: Menjaga Persaudaraan",
    ],
    "Pendidikan Pancasila": [
      "Bab 1: Nilai-Nilai Pancasila",
      "Bab 2: Hak Asasi Manusia",
      "Bab 3: Organisasi di Sekolah",
      "Bab 4: Bhinneka Tunggal Ika",
    ],
    "Bahasa Indonesia": [
      "Bab 1: Teks Eksplanasi",
      "Bab 2: Iklan dan Slogan",
      "Bab 3: Puisi dan Prosa",
      "Bab 4: Ringkasan dan Ide Pokok",
    ],
    Matematika: [
      "Bab 1: Pecahan dan Operasinya",
      "Bab 2: Skala dan Perbandingan",
      "Bab 3: Volume Kubus dan Balok",
      "Bab 4: Kecepatan dan Debit",
      "Bab 5: Statistika",
    ],
    "Ilmu Pengetahuan Alam dan Sosial (IPAS)": [
      "Bab 1: Cahaya dan Bunyi",
      "Bab 2: Sistem Pencernaan",
      "Bab 3: Magnet dan Listrik",
      "Bab 4: Siklus Air",
      "Bab 5: Keragaman Sosial Budaya",
    ],
    "Pendidikan Jasmani, Olahraga, dan Kesehatan": [
      "Bab 1: Permainan Bola Kecil",
      "Bab 2: Atletik Lanjutan",
      "Bab 3: Renang atau Aktivitas Air",
      "Bab 4: Pencegahan Penyakit",
    ],
    "Seni dan Budaya": [
      "Bab 1: Apresiasi Karya Seni",
      "Bab 2: Komposisi Musik",
      "Bab 3: Koreografi Sederhana",
      "Bab 4: Desain Produk",
    ],
    "Bahasa Inggris": [
      "Bab 1: Descriptive Text",
      "Bab 2: Asking for Information",
      "Bab 3: Past Activities",
      "Bab 4: Giving Directions",
    ],
    Informatika: [
      "Bab 1: Berpikir Komputasional",
      "Bab 2: Data dan Informasi",
      "Bab 3: Keamanan Digital",
      "Bab 4: Algoritma Sederhana",
    ],
    "Koding dan Kecerdasan Artifisial": [
      "Bab 1: Pengenalan Koding",
      "Bab 2: Blok Pemrograman",
      "Bab 3: AI di Kehidupan Sehari-hari",
      "Bab 4: Etika Digital",
    ],
    "Muatan Lokal": [
      "Bab 1: Wirausaha Daerah",
      "Bab 2: Flora dan Fauna Lokal",
      "Bab 3: Sejarah Lokal",
    ],
  },
  "6 SD": {
    "Pendidikan Agama dan Budi Pekerti": [
      "Bab 1: Mensyukuri Nikmat",
      "Bab 2: Ibadah sebagai Karakter",
      "Bab 3: Kepemimpinan yang Jujur",
      "Bab 4: Siap ke Jenjang Berikutnya",
    ],
    "Pendidikan Pancasila": [
      "Bab 1: Identitas Nasional",
      "Bab 2: Demokrasi di Sekolah",
      "Bab 3: Globalisasi dan Karakter",
      "Bab 4: Cinta NKRI",
    ],
    "Bahasa Indonesia": [
      "Bab 1: Teks Laporan",
      "Bab 2: Pidato dan Ringkasan",
      "Bab 3: Cerita Fiksi",
      "Bab 4: Persiapan Literasi AKM",
    ],
    Matematika: [
      "Bab 1: Pecahan dan Desimal",
      "Bab 2: Bangun Ruang",
      "Bab 3: Statistika Sederhana",
      "Bab 4: Perbandingan dan Skala",
      "Bab 5: Persiapan AKM Numerasi",
    ],
    "Ilmu Pengetahuan Alam dan Sosial (IPAS)": [
      "Bab 1: Sistem Tata Surya",
      "Bab 2: Perkembangbiakan Makhluk Hidup",
      "Bab 3: Energi dan Perubahannya",
      "Bab 4: Indonesia dan Dunia",
      "Bab 5: Perubahan Sosial",
    ],
    "Pendidikan Jasmani, Olahraga, dan Kesehatan": [
      "Bab 1: Permainan Tim",
      "Bab 2: Kebugaran untuk Prestasi",
      "Bab 3: Pertolongan Pertama",
      "Bab 4: Gaya Hidup Aktif",
    ],
    "Seni dan Budaya": [
      "Bab 1: Pameran Karya",
      "Bab 2: Pertunjukan Musik",
      "Bab 3: Pertunjukan Tari",
      "Bab 4: Portofolio Seni",
    ],
    "Bahasa Inggris": [
      "Bab 1: Procedure Text",
      "Bab 2: Recount Text",
      "Bab 3: Expressing Opinion",
      "Bab 4: Reading for Information",
    ],
    Informatika: [
      "Bab 1: Jaringan dan Internet",
      "Bab 2: Presentasi Digital",
      "Bab 3: Pengolahan Data",
      "Bab 4: Proyek Digital Sederhana",
    ],
    "Koding dan Kecerdasan Artifisial": [
      "Bab 1: Alur Logika Program",
      "Bab 2: Proyek Koding Mini",
      "Bab 3: Mengenali AI Generatif",
      "Bab 4: Tanggung Jawab Pengguna AI",
    ],
    "Muatan Lokal": [
      "Bab 1: Warisan Budaya",
      "Bab 2: Ekonomi Kreatif Daerah",
      "Bab 3: Pelestarian Lingkungan Lokal",
    ],
  },
  "7 SMP": {
    "Pendidikan Agama dan Budi Pekerti": [
      "Bab 1: Iman dan Taqwa",
      "Bab 2: Ibadah dan Karakter",
      "Bab 3: Adab Bergaul",
      "Bab 4: Menghormati Perbedaan",
    ],
    "Pendidikan Pancasila": [
      "Bab 1: Pancasila sebagai Dasar Negara",
      "Bab 2: Norma Hukum dan Keadilan",
      "Bab 3: Identitas Nasional",
      "Bab 4: Bhinneka Tunggal Ika",
    ],
    "Bahasa Indonesia": [
      "Bab 1: Teks Deskripsi",
      "Bab 2: Puisi",
      "Bab 3: Cerita Fantasi",
      "Bab 4: Surat Pribadi dan Dinas",
    ],
    Matematika: [
      "Bab 1: Bilangan Bulat dan Pecahan",
      "Bab 2: Perbandingan",
      "Bab 3: Bentuk Aljabar",
      "Bab 4: Persamaan Linear Satu Variabel",
      "Bab 5: Perbandingan dan Skala",
    ],
    "Ilmu Pengetahuan Alam": [
      "Bab 1: Zat dan Perubahannya",
      "Bab 2: Klasifikasi Makhluk Hidup",
      "Bab 3: Suhu, Kalor, dan Pemuaian",
      "Bab 4: Tata Surya",
      "Bab 5: Hakikat Ilmu Sains",
    ],
    "Ilmu Pengetahuan Sosial": [
      "Bab 1: Kehidupan Sosial",
      "Bab 2: Interaksi Sosial dan Lembaga",
      "Bab 3: Keadaan Alam Indonesia",
      "Bab 4: Aktivitas Ekonomi",
    ],
    "Bahasa Inggris": [
      "Bab 1: Greetings and Introductions",
      "Bab 2: Daily Activities",
      "Bab 3: Descriptive Text",
      "Bab 4: Asking and Giving Information",
    ],
    "Pendidikan Jasmani, Olahraga, dan Kesehatan": [
      "Bab 1: Permainan Bola Besar",
      "Bab 2: Atletik",
      "Bab 3: Senam",
      "Bab 4: Kesehatan Remaja",
    ],
    Informatika: [
      "Bab 1: Berpikir Komputasional",
      "Bab 2: Sistem Komputer",
      "Bab 3: Jaringan dan Internet",
      "Bab 4: Analisis Data",
    ],
    "Seni Budaya": [
      "Bab 1: Apresiasi Seni Rupa",
      "Bab 2: Musik Nusantara",
      "Bab 3: Tari Tradisional",
      "Bab 4: Teater",
    ],
    Prakarya: [
      "Bab 1: Kerajinan",
      "Bab 2: Rekayasa",
      "Bab 3: Budidaya",
      "Bab 4: Pengolahan",
    ],
    "Koding dan Kecerdasan Artifisial": [
      "Bab 1: Dasar Pemrograman",
      "Bab 2: Algoritma dan Logika",
      "Bab 3: Pengenalan AI",
      "Bab 4: Proyek Mini Koding",
    ],
    "Muatan Lokal": [
      "Bab 1: Bahasa dan Sastra Daerah",
      "Bab 2: Budaya Daerah",
      "Bab 3: Potensi Wilayah",
    ],
  },
  "8 SMP": {
    "Pendidikan Agama dan Budi Pekerti": [
      "Bab 1: Iman yang Kokoh",
      "Bab 2: Ibadah Sosial",
      "Bab 3: Menjaga Lisan dan Perbuatan",
      "Bab 4: Kepedulian Sosial",
    ],
    "Pendidikan Pancasila": [
      "Bab 1: Kedaulatan Rakyat",
      "Bab 2: Hak dan Kewajiban Warga Negara",
      "Bab 3: Persatuan Indonesia",
      "Bab 4: Semangat Kebangsaan",
    ],
    "Bahasa Indonesia": [
      "Bab 1: Teks Eksposisi",
      "Bab 2: Cerpen",
      "Bab 3: Drama",
      "Bab 4: Teks Persuasi",
    ],
    Matematika: [
      "Bab 1: Pola Bilangan",
      "Bab 2: Koordinat Kartesius",
      "Bab 3: Relasi dan Fungsi",
      "Bab 4: Teorema Pythagoras",
      "Bab 5: Lingkaran",
      "Bab 6: Statistika",
    ],
    "Ilmu Pengetahuan Alam": [
      "Bab 1: Pengenalan Sel",
      "Bab 2: Struktur dan Fungsi Tumbuhan",
      "Bab 3: Gaya dan Hukum Newton",
      "Bab 4: Usaha dan Energi",
      "Bab 5: Getaran, Gelombang, dan Bunyi",
    ],
    "Ilmu Pengetahuan Sosial": [
      "Bab 1: Kondisi Geografis Indonesia",
      "Bab 2: Perubahan Sosial",
      "Bab 3: Perdagangan dan Transportasi",
      "Bab 4: Pluralitas Masyarakat",
    ],
    "Bahasa Inggris": [
      "Bab 1: Recount Text",
      "Bab 2: Narrative Text",
      "Bab 3: Degrees of Comparison",
      "Bab 4: Invitation and Announcement",
    ],
    "Pendidikan Jasmani, Olahraga, dan Kesehatan": [
      "Bab 1: Permainan Bola Kecil",
      "Bab 2: Beladiri",
      "Bab 3: Aktivitas Ritmik",
      "Bab 4: NAPZA dan Kesehatan",
    ],
    Informatika: [
      "Bab 1: Algoritma dan Pemrograman",
      "Bab 2: Basis Data Sederhana",
      "Bab 3: Dampak Sosial Informatika",
      "Bab 4: Proyek Digital",
    ],
    "Seni Budaya": [
      "Bab 1: Seni Rupa Terapan",
      "Bab 2: Ansambel Musik",
      "Bab 3: Koreografi",
      "Bab 4: Pemeranan",
    ],
    Prakarya: [
      "Bab 1: Kerajinan Limbah",
      "Bab 2: Rekayasa Teknologi Tepat Guna",
      "Bab 3: Budidaya Ikan atau Tanaman",
      "Bab 4: Pengolahan Pangan",
    ],
    "Koding dan Kecerdasan Artifisial": [
      "Bab 1: Variabel dan Percabangan",
      "Bab 2: Perulangan",
      "Bab 3: Data untuk AI",
      "Bab 4: Etika AI",
    ],
    "Muatan Lokal": [
      "Bab 1: Sejarah Lokal",
      "Bab 2: Ekonomi Kreatif Daerah",
      "Bab 3: Pelestarian Budaya",
    ],
  },
  "9 SMP": {
    "Pendidikan Agama dan Budi Pekerti": [
      "Bab 1: Iman dan Tanggung Jawab",
      "Bab 2: Ibadah sebagai Jati Diri",
      "Bab 3: Menjaga Martabat Diri",
      "Bab 4: Siap Melanjutkan Pendidikan",
    ],
    "Pendidikan Pancasila": [
      "Bab 1: Negara Kesatuan Republik Indonesia",
      "Bab 2: Demokrasi Pancasila",
      "Bab 3: Wawasan Nusantara",
      "Bab 4: Belanegara",
    ],
    "Bahasa Indonesia": [
      "Bab 1: Teks Tanggapan",
      "Bab 2: Pidato Persuasif",
      "Bab 3: Cerita Inspiratif",
      "Bab 4: Karya Ilmiah Sederhana",
    ],
    Matematika: [
      "Bab 1: Perpangkatan dan Bentuk Akar",
      "Bab 2: Persamaan Kuadrat",
      "Bab 3: Perbandingan Senilai dan Berbalik Nilai",
      "Bab 4: Bangun Ruang Sisi Lengkung",
      "Bab 5: Statistika dan Peluang",
    ],
    "Ilmu Pengetahuan Alam": [
      "Bab 1: Sistem Reproduksi",
      "Bab 2: Pewarisan Sifat",
      "Bab 3: Listrik Dinamis",
      "Bab 4: Kemagnetan",
      "Bab 5: Bioteknologi",
      "Bab 6: Pemanasan Global",
    ],
    "Ilmu Pengetahuan Sosial": [
      "Bab 1: Interaksi Antarnegara ASEAN",
      "Bab 2: Perubahan Sosial Budaya",
      "Bab 3: Ketahanan Pangan dan Ekonomi",
      "Bab 4: Globalisasi",
    ],
    "Bahasa Inggris": [
      "Bab 1: Procedure Text",
      "Bab 2: Report Text",
      "Bab 3: Agreement and Disagreement",
      "Bab 4: Hope and Wish",
    ],
    "Pendidikan Jasmani, Olahraga, dan Kesehatan": [
      "Bab 1: Permainan Tim Lanjutan",
      "Bab 2: Kebugaran Jasmani",
      "Bab 3: Aktivitas di Alam",
      "Bab 4: Kesehatan Reproduksi",
    ],
    Informatika: [
      "Bab 1: Pemrograman Lanjutan",
      "Bab 2: Keamanan Siber",
      "Bab 3: Kecerdasan Artifisial Dasar",
      "Bab 4: Proyek Akhir Informatika",
    ],
    "Seni Budaya": [
      "Bab 1: Pameran Seni",
      "Bab 2: Pertunjukan Musik",
      "Bab 3: Pertunjukan Tari",
      "Bab 4: Produksi Teater",
    ],
    Prakarya: [
      "Bab 1: Wirausaha Kerajinan",
      "Bab 2: Rekayasa Produk",
      "Bab 3: Budidaya Produktif",
      "Bab 4: Pengolahan Pangan Lokal",
    ],
    "Koding dan Kecerdasan Artifisial": [
      "Bab 1: Proyek Aplikasi Sederhana",
      "Bab 2: Pengolahan Data",
      "Bab 3: Model AI Sederhana",
      "Bab 4: Presentasi Produk Digital",
    ],
    "Muatan Lokal": [
      "Bab 1: Identitas Daerah",
      "Bab 2: Keterampilan Lokal",
      "Bab 3: Siap ke SMA/SMK",
    ],
  },
  "10 SMA": {
    "Pendidikan Agama dan Budi Pekerti": [
      "Bab 1: Iman dan Ilmu",
      "Bab 2: Ibadah dan Karakter",
      "Bab 3: Akhlak dalam Kehidupan Modern",
      "Bab 4: Moderasi Beragama",
    ],
    "Pendidikan Pancasila": [
      "Bab 1: Pancasila sebagai Ideologi",
      "Bab 2: Identitas Nasional",
      "Bab 3: Hak Asasi Manusia",
      "Bab 4: Demokrasi dan Keadilan",
    ],
    "Bahasa Indonesia": [
      "Bab 1: Teks Laporan Hasil Observasi",
      "Bab 2: Teks Eksposisi",
      "Bab 3: Cerita Rakyat",
      "Bab 4: Debat",
    ],
    Matematika: [
      "Bab 1: Eksponen dan Logaritma",
      "Bab 2: Barisan dan Deret",
      "Bab 3: Vektor",
      "Bab 4: Trigonometri",
      "Bab 5: Sistem Persamaan Linear",
    ],
    "Bahasa Inggris": [
      "Bab 1: Narrative Text",
      "Bab 2: Descriptive Text",
      "Bab 3: Recount Text",
      "Bab 4: Announcement",
    ],
    Sejarah: [
      "Bab 1: Manusia dan Sejarah",
      "Bab 2: Penelitian Sejarah",
      "Bab 3: Indonesia pada Masa Praaksara",
      "Bab 4: Kerajaan Hindu-Buddha dan Islam",
    ],
    "Pendidikan Jasmani, Olahraga, dan Kesehatan": [
      "Bab 1: Permainan Bola Besar",
      "Bab 2: Kebugaran Jasmani",
      "Bab 3: Senam dan Ritmik",
      "Bab 4: Kesehatan dan Gizi",
    ],
    "Seni dan Budaya": [
      "Bab 1: Apresiasi Seni",
      "Bab 2: Berkarya Seni Rupa",
      "Bab 3: Musik",
      "Bab 4: Tari atau Teater",
    ],
    Informatika: [
      "Bab 1: Berpikir Komputasional",
      "Bab 2: Arsitektur Komputer",
      "Bab 3: Jaringan",
      "Bab 4: Analisis Data",
    ],
    "Prakarya dan Kewirausahaan": [
      "Bab 1: Peluang Usaha",
      "Bab 2: Perencanaan Produk",
      "Bab 3: Produksi",
      "Bab 4: Pemasaran",
    ],
    Fisika: [
      "Bab 1: Pengukuran",
      "Bab 2: Gerak Lurus",
      "Bab 3: Gerak Parabola dan Melingkar",
      "Bab 4: Hukum Newton",
      "Bab 5: Usaha dan Energi",
    ],
    Kimia: [
      "Bab 1: Hakikat Ilmu Kimia",
      "Bab 2: Struktur Atom",
      "Bab 3: Ikatan Kimia",
      "Bab 4: Stoikiometri",
      "Bab 5: Larutan Elektrolit",
    ],
    Biologi: [
      "Bab 1: Keanekaragaman Hayati",
      "Bab 2: Virus",
      "Bab 3: Klasifikasi Makhluk Hidup",
      "Bab 4: Ekologi",
    ],
    Ekonomi: [
      "Bab 1: Ilmu Ekonomi",
      "Bab 2: Masalah Ekonomi",
      "Bab 3: Permintaan dan Penawaran",
      "Bab 4: Pasar",
    ],
    Geografi: [
      "Bab 1: Pengetahuan Dasar Geografi",
      "Bab 2: Peta dan Penginderaan Jauh",
      "Bab 3: Dinamika Litosfer",
      "Bab 4: Atmosfer dan Hidrosfer",
    ],
    Sosiologi: [
      "Bab 1: Sosiologi sebagai Ilmu",
      "Bab 2: Hubungan Sosial",
      "Bab 3: Interaksi Sosial",
      "Bab 4: Sosialisasi",
    ],
    "Koding dan Kecerdasan Artifisial": [
      "Bab 1: Dasar Pemrograman",
      "Bab 2: Struktur Data Sederhana",
      "Bab 3: Konsep AI",
      "Bab 4: Proyek Digital",
    ],
    "Muatan Lokal": [
      "Bab 1: Bahasa Daerah",
      "Bab 2: Budaya Daerah",
      "Bab 3: Potensi Wilayah",
    ],
  },
  "11 SMA": {
    "Pendidikan Agama dan Budi Pekerti": [
      "Bab 1: Iman, Ilmu, dan Amal",
      "Bab 2: Etika dalam Bermuamalah",
      "Bab 3: Toleransi dan Kerukunan",
      "Bab 4: Dakwah dan Keteladanan",
    ],
    "Pendidikan Pancasila": [
      "Bab 1: Integrasi Nasional",
      "Bab 2: Sistem Hukum Indonesia",
      "Bab 3: Politik dan Demokrasi",
      "Bab 4: Ketahanan Nasional",
    ],
    "Bahasa Indonesia": [
      "Bab 1: Teks Prosedur",
      "Bab 2: Teks Eksplanasi",
      "Bab 3: Cerpen",
      "Bab 4: Resensi",
    ],
    Matematika: [
      "Bab 1: Induksi Matematika",
      "Bab 2: Program Linear",
      "Bab 3: Matriks",
      "Bab 4: Transformasi Geometri",
      "Bab 5: Turunan",
    ],
    "Matematika Lanjutan": [
      "Bab 1: Limit Fungsi",
      "Bab 2: Turunan Lanjutan",
      "Bab 3: Integral Dasar",
      "Bab 4: Peluang Lanjutan",
    ],
    "Bahasa Inggris": [
      "Bab 1: Analytical Exposition",
      "Bab 2: Hortatory Exposition",
      "Bab 3: Personal Letter",
      "Bab 4: Cause and Effect",
    ],
    Sejarah: [
      "Bab 1: Kolonialisme dan Imperialisme",
      "Bab 2: Pergerakan Nasional",
      "Bab 3: Proklamasi dan Revolusi",
      "Bab 4: Demokrasi Liberal dan Terpimpin",
    ],
    "Pendidikan Jasmani, Olahraga, dan Kesehatan": [
      "Bab 1: Permainan Tim",
      "Bab 2: Atletik Lanjutan",
      "Bab 3: Kebugaran untuk Prestasi",
      "Bab 4: Kesehatan Reproduksi",
    ],
    "Seni dan Budaya": [
      "Bab 1: Kritik Seni",
      "Bab 2: Berkarya Mandiri",
      "Bab 3: Pertunjukan",
      "Bab 4: Portofolio Seni",
    ],
    Informatika: [
      "Bab 1: Pemrograman",
      "Bab 2: Basis Data",
      "Bab 3: Keamanan Informasi",
      "Bab 4: Rekayasa Perangkat Lunak",
    ],
    "Prakarya dan Kewirausahaan": [
      "Bab 1: Model Bisnis",
      "Bab 2: Keuangan Usaha",
      "Bab 3: Branding",
      "Bab 4: Digital Marketing",
    ],
    Fisika: [
      "Bab 1: Kinematika",
      "Bab 2: Dinamika Rotasi",
      "Bab 3: Elastisitas dan Fluida",
      "Bab 4: Teori Kinetik Gas",
      "Bab 5: Termodinamika",
    ],
    Kimia: [
      "Bab 1: Laju Reaksi",
      "Bab 2: Kesetimbangan Kimia",
      "Bab 3: Asam Basa",
      "Bab 4: Titrasi",
      "Bab 5: Hidrolisis Garam",
    ],
    Biologi: [
      "Bab 1: Sel",
      "Bab 2: Sistem Gerak",
      "Bab 3: Sistem Peredaran Darah",
      "Bab 4: Sistem Pencernaan",
      "Bab 5: Sistem Pernapasan",
    ],
    Ekonomi: [
      "Bab 1: Pendapatan Nasional",
      "Bab 2: Uang dan Perbankan",
      "Bab 3: Kebijakan Fiskal dan Moneter",
      "Bab 4: APBN dan APBD",
    ],
    Geografi: [
      "Bab 1: Flora dan Fauna Indonesia",
      "Bab 2: Kependudukan",
      "Bab 3: Sumber Daya Alam",
      "Bab 4: Mitigasi Bencana",
    ],
    Sosiologi: [
      "Bab 1: Kelompok Sosial",
      "Bab 2: Permasalahan Sosial",
      "Bab 3: Konflik dan Integrasi",
      "Bab 4: Lembaga Sosial",
    ],
    Antropologi: [
      "Bab 1: Hakikat Antropologi",
      "Bab 2: Kebudayaan",
      "Bab 3: Religi dan Masyarakat",
      "Bab 4: Perubahan Budaya",
    ],
    "Bahasa Asing": [
      "Bab 1: Kosakata Dasar",
      "Bab 2: Tata Bahasa Dasar",
      "Bab 3: Percakapan Sehari-hari",
      "Bab 4: Budaya Penutur Asli",
    ],
    "Koding dan Kecerdasan Artifisial": [
      "Bab 1: Pemrograman Berorientasi Objek",
      "Bab 2: API dan Data",
      "Bab 3: Machine Learning Dasar",
      "Bab 4: Proyek AI",
    ],
    "Muatan Lokal": [
      "Bab 1: Kearifan Lokal",
      "Bab 2: Kewirausahaan Daerah",
      "Bab 3: Riset Lingkungan Setempat",
    ],
  },
  "12 SMA": {
    "Pendidikan Agama dan Budi Pekerti": [
      "Bab 1: Spiritualitas dan Profesionalitas",
      "Bab 2: Etika Kerja",
      "Bab 3: Kontribusi Sosial",
      "Bab 4: Siap Kehidupan Lanjut",
    ],
    "Pendidikan Pancasila": [
      "Bab 1: Geopolitik Indonesia",
      "Bab 2: Hubungan Internasional",
      "Bab 3: Kasus Aktual Kebangsaan",
      "Bab 4: Peran Warga Negara Global",
    ],
    "Bahasa Indonesia": [
      "Bab 1: Surat Lamaran Kerja",
      "Bab 2: Teks Editorial",
      "Bab 3: Novel",
      "Bab 4: Artikel Ilmiah Populer",
    ],
    Matematika: [
      "Bab 1: Geometri Ruang",
      "Bab 2: Integral",
      "Bab 3: Statistika Inferensial",
      "Bab 4: Peluang",
    ],
    "Matematika Lanjutan": [
      "Bab 1: Integral Lanjutan",
      "Bab 2: Dimensi Tiga",
      "Bab 3: Statistika Lanjutan",
      "Bab 4: Limit dan Turunan Aplikasi",
    ],
    "Bahasa Inggris": [
      "Bab 1: News Item",
      "Bab 2: Caption",
      "Bab 3: Application Letter",
      "Bab 4: Review Text",
    ],
    Sejarah: [
      "Bab 1: Orde Baru",
      "Bab 2: Reformasi",
      "Bab 3: Indonesia dalam Dunia Global",
      "Bab 4: Historiografi Indonesia",
    ],
    "Pendidikan Jasmani, Olahraga, dan Kesehatan": [
      "Bab 1: Olahraga Prestasi",
      "Bab 2: Manajemen Kebugaran",
      "Bab 3: Pencegahan Cedera",
      "Bab 4: Gaya Hidup Sehat Dewasa",
    ],
    "Seni dan Budaya": [
      "Bab 1: Pameran Akhir",
      "Bab 2: Produksi Pertunjukan",
      "Bab 3: Manajemen Seni",
      "Bab 4: Portofolio Karier Seni",
    ],
    Informatika: [
      "Bab 1: Proyek Perangkat Lunak",
      "Bab 2: Data Sains Dasar",
      "Bab 3: Keamanan Siber",
      "Bab 4: Portofolio Digital",
    ],
    "Prakarya dan Kewirausahaan": [
      "Bab 1: Skala Usaha",
      "Bab 2: Analisis Kelayakan",
      "Bab 3: Inkubasi Produk",
      "Bab 4: Pitching Usaha",
    ],
    Fisika: [
      "Bab 1: Listrik Statis",
      "Bab 2: Listrik Dinamis",
      "Bab 3: Medan Magnet",
      "Bab 4: Induksi Elektromagnetik",
      "Bab 5: Gelombang Elektromagnetik",
    ],
    Kimia: [
      "Bab 1: Sifat Koligatif Larutan",
      "Bab 2: Redoks dan Elektrokimia",
      "Bab 3: Kimia Unsur",
      "Bab 4: Senyawa Karbon",
      "Bab 5: Kimia Makromolekul",
    ],
    Biologi: [
      "Bab 1: Pertumbuhan dan Perkembangan",
      "Bab 2: Metabolisme",
      "Bab 3: Genetika",
      "Bab 4: Evolusi",
      "Bab 5: Bioteknologi",
    ],
    Ekonomi: [
      "Bab 1: Akuntansi Dasar",
      "Bab 2: Manajemen",
      "Bab 3: Koperasi dan UMKM",
      "Bab 4: Ekonomi Internasional",
    ],
    Geografi: [
      "Bab 1: Pola Keruangan Desa dan Kota",
      "Bab 2: Interaksi Desa-Kota",
      "Bab 3: Pembangunan Berkelanjutan",
      "Bab 4: Geografi Regional",
    ],
    Sosiologi: [
      "Bab 1: Perubahan Sosial",
      "Bab 2: Modernisasi dan Globalisasi",
      "Bab 3: Ketimpangan Sosial",
      "Bab 4: Penelitian Sosial",
    ],
    Antropologi: [
      "Bab 1: Identitas Budaya",
      "Bab 2: Etnisitas",
      "Bab 3: Antropologi Terapan",
      "Bab 4: Isu Budaya Kontemporer",
    ],
    "Bahasa Asing": [
      "Bab 1: Percakapan Formal",
      "Bab 2: Teks Fungsional",
      "Bab 3: Presentasi",
      "Bab 4: Budaya dan Etika Komunikasi",
    ],
    "Koding dan Kecerdasan Artifisial": [
      "Bab 1: Rekayasa Produk Digital",
      "Bab 2: Evaluasi Model AI",
      "Bab 3: Privasi dan Tata Kelola AI",
      "Bab 4: Portofolio Proyek",
    ],
    "Muatan Lokal": [
      "Bab 1: Kajian Daerah",
      "Bab 2: Inovasi Lokal",
      "Bab 3: Pengabdian Masyarakat",
    ],
  },
};

export const DAFTAR_KELAS = Object.keys(DATA_KURIKULUM);

export const OPSI_LAINNYA = "LAINNYA";

export function daftarMapelUnik(): string[] {
  const nama = new Set<string>();
  for (const mapelKelas of Object.values(DATA_KURIKULUM)) {
    for (const mapel of Object.keys(mapelKelas)) nama.add(mapel);
  }
  return [...nama].sort((a, b) => a.localeCompare(b, "id"));
}

export function daftarMateriUntukMapel(mapel: string): string[] {
  const materi = new Set<string>();
  for (const mapelKelas of Object.values(DATA_KURIKULUM)) {
    for (const bab of mapelKelas[mapel] ?? []) materi.add(bab);
  }
  return [...materi];
}
